"""add season external_id

Revision ID: a4b001d3c1bb
Revises: 50137c1f3fe6
Create Date: 2026-09-22 00:47:50.199844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b001d3c1bb'
down_revision: Union[str, Sequence[str], None] = '50137c1f3fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season', sa.Column('external_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_season_external_id', 'season', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_season_external_id', 'season', type_='unique')
    op.drop_column('season', 'external_id')
    # ### end Alembic commands ###
