"""add unique standing season team

Revision ID: b88b48e25165
Revises: a4b001d3c1bb
Create Date: 2026-09-22 01:02:54.258061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88b48e25165'
down_revision: Union[str, Sequence[str], None] = 'a4b001d3c1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_standing_season_team', 'standing', ['season_id', 'team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_standing_season_team', 'standing', type_='unique')
    # ### end Alembic commands ###
